# BEGIN_KITTY_THEME
# Aquarium Dark
# MOST OF THIS CONFIG WAS MADE BY RUST1XXX!!! https://github>
enable_background_opacity yes
background_opacity 0.17
include current-theme.conf
confirm_os_window_close 0
background #000000
foreground #98FF98
cursor #98FF98
window_padding_width 10
hide_window_decorations yes
tab_bar_style hidden
window_border_width 1pt
active_border_color #98FF98
inactive_border_color #98FF98
window_margin_width 1
color1 #98FF98
color9 #98FF98
# END_KITTY_THEME
